CREATE DATABASE EctoTec

CREATE TABLE PAIS(
Id INT PRIMARY KEY IDENTITY(1,1),
Nombre VARCHAR(30) NOT NULL
);

CREATE TABLE ENTIDAD(
Id INT PRIMARY KEY IDENTITY(1,1),
IdPais INT NOT NULL,
Nombre VARCHAR (30),
CONSTRAINT FK_EntidadPais FOREIGN KEY (IdPais)REFERENCES PAIS(Id)
);

CREATE TABLE CIUDAD(
Id INT PRIMARY KEY IDENTITY(1,1),
IdEntidd INT NOT NULL,
Nombre VARCHAR(30),
CONSTRAINT FK_CiudadEntidad FOREIGN KEY (IdEntidd)REFERENCES ENTIDAD(Id)
);


CREATE TABLE USUARIO(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Nombre VARCHAR (30) NOT NULL,
Mail VARCHAR (50) NOT NULL,
Telefono VARCHAR(10) NOT NULL,
Fecha DATE NOT NULL,
IdCiudad INT NOT NULL,
CONSTRAINT FK_UsuarioCiudad FOREIGN KEY (IdCiudad)REFERENCES CIUDAD(Id)
);
